import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import * as React from 'react';
import { CssVarsProvider } from '@mui/joy/styles';
import Sheet from '@mui/joy/Sheet';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssVarsProvider>
        <Sheet variant="outlined">
        {children}          
          </Sheet>
        </CssVarsProvider>
        </body>
    </html>
  );
}
